from lista_doblemente_enlazada import ListaDoblementeEnlazada
lista=ListaDoblementeEnlazada()
lista.agregar_final(12)
lista.agregar_final(14)
lista.agregar_final(16)
lista.agregar_final(18)
lista.agregar_final(20)
lista.agregar_final(22)
lista.agregar_inicio(10)
lista.recorrer_inicio()
print("=========")
lista.get_size()
print("=========")
lista.eliminar_final()
print("=========")
lista.eliminar_inicio()
print("=========")
lista.recorrer_fin()
print("=========")

